#!/usr/bin/env python3
"""Reduce a HICAR namelist to only the entries that differ from the defaults.

Given the freshly generated default namelist and an "example" namelist (the
default with some entries find/replaced to non-default values), emit a minimal
namelist that keeps ONLY the customized entries — so a user reading the example
sees just what that example changes, not all ~340 options.

Variables whose name contains "folder" (e.g. the output / restart folder paths)
are ALWAYS kept, even at their default value, so each example clearly documents
where its output and restart files are written.

Empty sections are KEPT as a bare `&section /` header, never deleted: HICAR
reads its always-present sections (general, restart, domain, forcing, physics,
time_parameters, output) unconditionally, and a *missing* group makes the
namelist read hit end-of-file and `stop` the model. An empty *present* group
reads fine and leaves every value at its in-code default.

Usage:
    strip_defaults.py <default.nml> <example.nml> <out.nml> [--title TEXT]
"""
import argparse
import re
import sys

SECTION_RE = re.compile(r"^\s*&(\w+)")
END_RE = re.compile(r"^\s*/\s*$")
VAR_RE = re.compile(r"^\s*([A-Za-z]\w*)\s*=\s*(.*)$")


def strip_comment(value):
    """Drop a trailing Fortran `!` comment, respecting single/double quotes."""
    out = []
    quote = None
    for ch in value:
        if quote:
            out.append(ch)
            if ch == quote:
                quote = None
        elif ch in "'\"":
            quote = ch
            out.append(ch)
        elif ch == "!":
            break
        else:
            out.append(ch)
    return "".join(out).strip()


def parse(path):
    """Return an ordered list of (section, [(var, value_norm, raw_line)])."""
    sections = []
    current = None
    with open(path) as fh:
        for raw in fh:
            line = raw.rstrip("\n")
            m = SECTION_RE.match(line)
            if m:
                current = (m.group(1), [])
                sections.append(current)
                continue
            if current is None:
                continue
            if END_RE.match(line):
                current = None
                continue
            vm = VAR_RE.match(line)
            if vm:
                name = vm.group(1)
                value_norm = strip_comment(vm.group(2))
                current[1].append((name, value_norm, line.rstrip()))
            # else: blank or continuation-comment line -> ignored
    return sections


def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("default")
    p.add_argument("example")
    p.add_argument("out")
    p.add_argument("--title", default="HICAR example namelist (auto-generated)")
    args = p.parse_args()

    # default values: {section: {var: value_norm}}
    defaults = {}
    for sec, entries in parse(args.default):
        defaults.setdefault(sec, {})
        for name, value, _ in entries:
            defaults[sec][name] = value

    example = parse(args.example)

    n_kept = 0
    out_lines = [
        f"! {args.title}",
        "! ---------------------------------------------------------------------------",
        "! Auto-generated by helpers/example_namelists/generate_examples.sh — DO NOT EDIT.",
        "! Only entries that differ from the model defaults are shown (plus the",
        "! output/restart folder paths, always listed); every other option keeps",
        "! its default value. Empty sections are retained on purpose",
        "! (removing an always-read section makes HICAR stop at namelist read).",
        "! Generate the full annotated default with:  ./bin/HICAR --gen-nml default.nml",
        "! ---------------------------------------------------------------------------",
        "",
    ]
    for sec, entries in example:
        out_lines.append(f" &{sec}")
        sec_defaults = defaults.get(sec, {})
        for name, value, raw in entries:
            # Keep an entry if it is customized (differs from / absent in the
            # defaults) OR if its name contains "folder" — output/restart folder
            # paths are always shown so the example documents where files land,
            # even when left at the default.
            if sec_defaults.get(name) != value or "folder" in name.lower():
                out_lines.append(raw)
                n_kept += 1
        out_lines.append(" /")
        out_lines.append("")

    with open(args.out, "w") as fh:
        fh.write("\n".join(out_lines) + "\n")

    print(f"  {args.out}: kept {n_kept} non-default entries across "
          f"{len(example)} sections")


if __name__ == "__main__":
    main()
